 // Failed to get sources. Instead, stub sources have been generated by the disassembler.
 // Implementation of methods is unavailable.
public class World {
  
  private int size;
  
  private java.lang.String[][] w;
  
  private int pX;
  
  private int pY;
  
  private boolean wumpusAlive;
  
  private boolean hasArrow;
  
  private boolean isInPit;
  
  private boolean hasGold;
  
  private boolean gameOver;
  
  private int score;
  
  public static final int DIR_UP = 0;
  
  public static final int DIR_RIGHT = 1;
  
  public static final int DIR_DOWN = 2;
  
  public static final int DIR_LEFT = 3;
  
  private int dir;
  
  public static final java.lang.String BREEZE = "B";
  
  public static final java.lang.String STENCH = "S";
  
  public static final java.lang.String PIT = "P";
  
  public static final java.lang.String WUMPUS = "W";
  
  public static final java.lang.String GLITTER = "G";
  
  public static final java.lang.String GOLD = "T";
  
  public static final java.lang.String UNKNOWN = "U";
  
  public static final java.lang.String A_MOVE = "m";
  
  public static final java.lang.String A_MOVE_UP = "mU";
  
  public static final java.lang.String A_MOVE_DOWN = "mD";
  
  public static final java.lang.String A_MOVE_LEFT = "mL";
  
  public static final java.lang.String A_MOVE_RIGHT = "mR";
  
  public static final java.lang.String A_GRAB = "g";
  
  public static final java.lang.String A_CLIMB = "c";
  
  public static final java.lang.String A_SHOOT = "s";
  
  public static final java.lang.String A_SHOOT_UP = "sU";
  
  public static final java.lang.String A_SHOOT_DOWN = "sD";
  
  public static final java.lang.String A_SHOOT_LEFT = "sL";
  
  public static final java.lang.String A_SHOOT_RIGHT = "sR";
  
  public static final java.lang.String A_TURN_LEFT = "l";
  
  public static final java.lang.String A_TURN_RIGHT = "r";
  
  public World(int arg0) {
  }
  
  public int getScore() {
    return 0;
  }
  
  public int getSize() {
    return 0;
  }
  
  public boolean gameOver() {
    return false;
  }
  
  public int getPlayerX() {
    return 0;
  }
  
  public int getPlayerY() {
    return 0;
  }
  
  public boolean isInPit() {
    return false;
  }
  
  public boolean hasArrow() {
    return false;
  }
  
  public boolean wumpusAlive() {
    return false;
  }
  
  public boolean hasGold() {
    return false;
  }
  
  public int getDirection() {
    return 0;
  }
  
  public boolean hasBreeze(int arg0, int arg1) {
    return false;
  }
  
  public boolean hasStench(int arg0, int arg1) {
    return false;
  }
  
  public boolean hasGlitter(int arg0, int arg1) {
    return false;
  }
  
  public boolean hasPit(int arg0, int arg1) {
    return false;
  }
  
  public boolean hasWumpus(int arg0, int arg1) {
    return false;
  }
  
  public boolean hasPlayer(int arg0, int arg1) {
    return false;
  }
  
  public boolean isVisited(int arg0, int arg1) {
    return false;
  }
  
  public boolean isUnknown(int arg0, int arg1) {
    return false;
  }
  
  public boolean isValidPosition(int arg0, int arg1) {
    return false;
  }
  
  private void append(int arg0, int arg1, java.lang.String arg2) {
  }
  
  public void addWumpus(int arg0, int arg1) {
  }
  
  public void addPit(int arg0, int arg1) {
  }
  
  public void addGold(int arg0, int arg1) {
  }
  
  private void setVisited(int arg0, int arg1) {
  }
  
  public boolean doAction(java.lang.String arg0) {
    return false;
  }
  
  private void shoot() {
  }
  
  private void removeWumpus() {
  }
  
  private boolean move(int arg0, int arg1) {
    return false;
  }
}